import { encrypt } from "../config/Encryption"

export const userConstent = {
    USER_LOGIN_REQUEST : 'USER_LOGIN_REQUEST',
    USER_LOGIN_SUCCESS : 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAILEAR : 'USER_LOGIN_FAILEAR',

    SPORT_MATCHLIST_REQUEST : 'SPORT_MATCHLIST_REQUEST',
    SPORT_MATCHLIST_SUCCESS : 'SPORT_MATCHLIST_SUCCESS',
    SPORT_MATCHLIST_FAILEAR : 'SPORT_MATCHLIST_FAILEAR',

    LOGOUT: 'USERS_LOGOUT',
}

const CLIENT_TASK_STATUS_PENDING = "Pending"
const CLIENT_TASK_STATUS_REJECT = "Rejected"
const CLIENT_TASK_STATUS_ASSIGNED = "Assigned"
const CLIENT_TASK_STATUS_RESTART = "re_start"
const CLIENT_TASK_STATUS_REASSIGNED = "re_assigned"
const CLIENT_TASK_STATUS_REQ_REJECTED = "request_rejected"
const CLIENT_TASK_STATUS_ACCEPTED = "Accepted"
const CLIENT_TASK_STATUS_REASSIGN_TO_OTHER = "reAssign_to_other"
const CLIENT_TASK_STATUS_PENDING_AT_CLIENT = "Pending_at_client"
const CLIENT_TASK_STATUS_PENDING_AT_DEPARTMENT = "Pending_at_department"
const CLIENT_TASK_STATUS_PENDING_AT_COLLEAGUE = "Pending_at_colleague"
const CLIENT_TASK_STATUS_PENDING_AT_MANAGER = "Pending_at_manager"
const CLIENT_TASK_STATUS_WORK_IN_PROGRESS = "Work_in_progress"
const CLIENT_TASK_STATUS_PENDING_FOR_FEE = "Pending_for_fees"
const CLIENT_TASK_STATUS_COMPLETED = "Completed"
const CLIENT_TASK_STATUS_STOP = "Task_Stop"
const CLIENT_TASK_STATUS_PENDING_FOR_APPROVAL = "Pending_for_approval"
export const CLIENT_TASK_STATUS_ARR = [
    CLIENT_TASK_STATUS_PENDING,
    CLIENT_TASK_STATUS_REJECT,
    CLIENT_TASK_STATUS_ASSIGNED,
    CLIENT_TASK_STATUS_RESTART,
    CLIENT_TASK_STATUS_REASSIGNED,
    CLIENT_TASK_STATUS_REQ_REJECTED,
    CLIENT_TASK_STATUS_ACCEPTED,
    CLIENT_TASK_STATUS_REASSIGN_TO_OTHER,
    CLIENT_TASK_STATUS_PENDING_AT_CLIENT,
    CLIENT_TASK_STATUS_PENDING_AT_DEPARTMENT,
    CLIENT_TASK_STATUS_PENDING_AT_COLLEAGUE,
    CLIENT_TASK_STATUS_PENDING_AT_MANAGER,
    CLIENT_TASK_STATUS_WORK_IN_PROGRESS,
    CLIENT_TASK_STATUS_PENDING_FOR_APPROVAL,
    CLIENT_TASK_STATUS_PENDING_FOR_FEE,
    CLIENT_TASK_STATUS_COMPLETED,
    CLIENT_TASK_STATUS_STOP,
]
const TASK_PRIORITY_HIGH = "high"
const TASK_PRIORITY_MEDIUM = "medium"
const TASK_PRIORITY_LOW = "low"

export const PRIORITY = [
    TASK_PRIORITY_HIGH,
    TASK_PRIORITY_MEDIUM,
    TASK_PRIORITY_LOW

]

export const leadManagementStatus = ['New', 'Converted', 'Contacted', 'Qualified', 'Working', 'ProposalSent', 'Closed']




const LEAD_FOLLOWUP_TYPE_CALL = "Call"
const LEAD_FOLLOWUP_TYPE_EMAIL = "Email"
const LEAD_FOLLOWUP_TYPE_MEETING = "Meeting"
const LEAD_FOLLOWUP_TYPE_DEMO = "Demo"
const LEAD_FOLLOWUP_TYPE_PROPOSAL = "Proposal"
const LEAD_FOLLOWUP_TYPE_MESSAGE = "Message"
const LEAD_FOLLOWUP_TYPE_OTHER = "Other"
export const LEAD_FOLLOWUP_TYPE_ARR = [LEAD_FOLLOWUP_TYPE_CALL, LEAD_FOLLOWUP_TYPE_EMAIL, LEAD_FOLLOWUP_TYPE_MEETING, LEAD_FOLLOWUP_TYPE_DEMO, LEAD_FOLLOWUP_TYPE_PROPOSAL, LEAD_FOLLOWUP_TYPE_MESSAGE, LEAD_FOLLOWUP_TYPE_OTHER]